name: rive_animated_icon
description: "A new Flutter project."
version: 0.1.0
repository: https://github.com/nikkieke/rive_animated_icons
issue_tracker: https://github.com/nikkieke/rive_animated_icons/issues

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rive: ^0.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/